### ISSUE TITLE
wrong syntax

### ISSUE THREAD

**Issue by tcheksa62** [Nexinto/go-icinga2-client#3]
Hello,

/plusserver/go-icinga2-client/icinga2/service.go:65:76: resp.HttpResponse().StatusCodem undefined (type *http.Response has no field or method StatusCodem)

right syntax is "StatusCode"

**Comment by erlisb** [comment]
@tcheksa62, I have also faced this issue.
Best solution would be to fork this repo and extend/modify according to your needs.
It seems that this repo is not maintained any more.

@ShuzZzle any info ?

Thnx.

**Comment by diceone** [comment]
Fixed
